services:
  elasticsearch:
    image: elasticsearch:8.14.3
    volumes:
      - es_data:/es_data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  es_data:
